apiVersion: v1
kind: Secret
data:
  {{- if .Values.setEncryptionSecretData -}}
  {{- include "alert.encryptionSecretEnvirons" . | nindent 2 }}
  {{- end }}
  {{- if .Values.secretEnvirons }}
  {{ .Values.secretEnvirons | toYaml | trimSuffix "\n" | nindent 2 }}
  {{- end }}
metadata:
  labels:
    app: alert
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}-alert-environs-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
---