version: '2.3'
services:
#  alert:
#    # uncomment environment to set environment variables for the alert service.
#    environment:
#      - ALERT_HOSTNAME=localhost
#    # uncomment volumes in order to mount a directory containing the Alert files to /run/secrets of the container.
#    volumes: ['<PATH_TO_SECRETS>:/run/secrets']
