version: '3.6'
services:
#  alert:
#    # uncomment environment to set environment variables for the alert service.
#    environment:
#      - ALERT_HOSTNAME=localhost
#    # uncomment the secrets section to use secrets.
#    # Please uncomment the secrets in use; both the required and the optional secrets.
#    # Note: choose one jssecacerts or cacerts secret not both.
#    secrets:
#      - ALERT_ENCRYPTION_PASSWORD
#      - ALERT_ENCRYPTION_GLOBAL_SALT
#      - WEBSERVER_CUSTOM_CERT_FILE
#      - WEBSERVER_CUSTOM_KEY_FILE
#      - jssecacerts
#      - cacerts
#
# uncomment the secrets in use; both the required and the optional secrets.
#secrets:
#  ALERT_ENCRYPTION_PASSWORD:
#    external: true
#    name: "<STACK_NAME>_ALERT_ENCRYPTION_PASSWORD"
#  ALERT_ENCRYPTION_GLOBAL_SALT:
#    external: true
#    name: "<STACK_NAME>_ALERT_ENCRYPTION_GLOBAL_SALT"
#  WEBSERVER_CUSTOM_CERT_FILE:
#    external: true
#    name: "<STACK_NAME>_WEBSERVER_CUSTOM_CERT_FILE"
#  WEBSERVER_CUSTOM_KEY_FILE:
#    external: true
#    name: "<STACK_NAME>_WEBSERVER_CUSTOM_KEY_FILE"
#  jssecacerts:
#    external: true
#    name: "<STACK_NAME>_jssecacerts"
#  cacerts:
#    external: true
#    name: "<STACK_NAME>_cacerts"
