version: '2.3'
services:
  alert:
    image: blackducksoftware/blackduck-alert:VERSION_TOKEN
    ports: ['8443:8443']
    links: [cfssl]
    env_file: [blackduck-alert.env]
    user: alert:root
    healthcheck:
      test: [CMD, /usr/local/bin/docker-healthcheck.sh, 'https://localhost:8443/alert/api/about',
             /opt/blackduck/alert/security/root.crt, /opt/blackduck/alert/security/blackduck_system.crt,
             /opt/blackduck/alert/security/blackduck_system.key]
      interval: 30s
      timeout: 60s
      retries: 15
    volumes: ['alert-db-volume:/opt/blackduck/alert/alert-config/data']
    mem_limit: 2560M
volumes: {alert-db-volume: null}
