---
apiVersion: v1
data:
    {{- if not .Values.alertdb.isExternal }}
    ALERT_DB_HOST: {{ .Release.Name }}-alert-postgres
    {{- else }}
    ALERT_DB_HOST: {{ .Values.alertdb.host }}
    {{- end }}
    ALERT_DB_PORT: {{ .Values.alertdb.port | quote }}
    ALERT_DB_USERNAME: {{ .Values.alertdb.userUserName }}
    ALERT_DB_NAME: {{ .Values.alertdb.databaseName }}
kind: ConfigMap
metadata:
  labels:
    app: alert
    component: alertdb
  name: {{ .Release.Name }}-alert-db-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  ALERT_POSTGRES_USER_PASSWORD_FILE: {{ .Values.alertdb.userPassword | b64enc }}
kind: Secret
metadata:
  labels:
    app: alert
    component: alertdb
  name: {{ .Release.Name }}-alert-db-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
