# Values for Alert.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# alert - configurations for the Alert Pod
alert:
  image: "docker.io/blackducksoftware/blackduck-alert:VERSION_TOKEN"
  limitMemory: "2560M"
  requestMemory: "2560M"
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Set if Alert will be deployed with a Black Duck instance
deployAlertWithBlackDuck: false
# enableStandalone deploys a cfssl instance with Alert
enableStandalone: true
cfssl:
  image: "docker.io/blackducksoftware/blackduck-cfssl:1.0.0"
  limitMemory: "640M"
  requestMemory: "640M"
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Storage configurations
enablePersistentStorage: false
pvcSize: "5G"
storageClassName: ""

# Expose Alert's User Interface
exposeui: true
exposedServiceType: NodePort # ClusterIP | NodePort | LoadBalancer

# environs is a list of *additional* environs to add to the Alert's ConfigMap
# The follwing environs are already set in the ConfigMap
# at /templates/alert-environ-resources.yaml (go there to set them):
#   - PUBLIC_HUB_WEBSERVER_HOST
#   - HUB_WEBAPP_HOST
#   - HUB_CFSSL_HOST
#   - PUBLIC_HUB_WEBSERVER_PORT
#   - ALERT_SERVER_PORT
#   - PUBLIC_HUB_WEBSERVER_PORT
# Format: array of strings delimited by commas; each string has the format "KEY:VALUE" e.g. ["PUBLIC_HUB_WEBSERVER_HOST:localhost", "PUBLIC_HUB_WEBSERVER_PORT:443"]
environs: []

# secretEnvirons is a list of environs to add to the Alert's Secret
# The follwing environs are handled by setting .Values.setEncryptionSecretData:
#   - ALERT_ENCRYPTION_PASSWORD
#   - ALERT_ENCRYPTION_GLOBAL_SALT
# Format: array of strings delimited by commas; each string has the format "KEY:VALUE" e.g. ["KEY:VALUE", "KEY:VALUE"]
secretEnvirons: []

# If true, requires the user to set alertEncryptionPassword and alertEncryptionGlobalSalt
setEncryptionSecretData: false

# Alert's certificate information
enableCertificateSecret: false
